
name: Run Playwright Login Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #  Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      #  Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      #  Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run only login.spec.js
      - name: Run Playwright login test
        run: npx playwright test SmokeTests/login.spec.js --reporter=html

      #  Upload HTML report
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
